In [1]:
import sympy
import numpy as np
from sympy import *
import pandas as pd
import re
x, y, z = symbols("x y z")

In [6]:
def generate_factorization_questions(a):
    a = list(np.random.randint(-a, a +1, size=1))
    c = list(np.random.randint(-20, 21, size=1))
    if a[0] == 0:
        a = np.random.randint(1, 5, size=1)[0]
    else:
        a = a[0]
    
    if c[0] == 0:
        c = np.random.randint(1, 21, size=1)[0]
    else:
        c = c[0]
  
  
    
    ac = a * c
    if ac > 0:
        ac_range = range(-ac, ac + 1)
    else:
        ac_range = range(ac, -ac + 1)
   
    b_list = [(b1, b2) for b1 in ac_range for b2 in ac_range if (b1 * b2 == ac)]
    pos_b = len(b_list)
    if pos_b == 0:
        pos_b_index = 0
    else:
        pos_b_index = np.random.randint(0, pos_b )
    
    b_pair = b_list[pos_b_index]
    b = sum(b_pair)
    
    test = (a, b, c)
    
    
    sym_eq = a * x ** 2 + b * x + c
    
         
    if a == 1:
        a = ""
    if a == -1:
        a = '-'
    if b == 1:
        b = ""
    if b == -1:
        b = '-'
  
        
    eq2 = '{}x\u00b2 + {}x + {}'.format(a, b, c)
        
           
    eq2 = re.sub(r'[+] [-]', '-', eq2)
    
    
    return eq2, sym_eq.factor()

In [7]:
generate_factorization_questions(6)

('-x² + 2x + 15', -(x - 5)*(x + 3))

In [31]:
def generate_spreadheet(num_questions, sheet_name, max_a=6):
    questions = []
    answers = []
    for i in range(num_questions):
        q, a = generate_factorization_questions(max_a)
        questions.append(q)
        answers.append(a)
        database = {'questions': questions, 'answers': answers}
        df = pd.DataFrame(database)
        df['answers'] = df['answers'].apply(str)
        df['answers'] = df['answers'].replace(')**2', ')\u00b2')
        df['answers'] = df['answers'].apply(lambda x: re.sub(r'[*]', '', x))
        df.to_excel(sheet_name)
        
    return df

In [32]:
generate_spreadheet(1001, '1001 Factorization Questions.xlsx', 7)

           questions             answers
0        7x² -18x -9     (x - 3)(7x + 3)
1       4x² -10x + 6    2(x - 1)(2x - 3)
2     6x² + 31x + 18    (2x + 9)(3x + 2)
3     -4x² + 28x -13  -(2x - 13)(2x - 1)
4       4x² -16x + 7    (2x - 7)(2x - 1)
...              ...                 ...
996    -5x² + 12x -7    -(x - 1)(5x - 7)
997   -4x² + 17x -18    -(x - 2)(4x - 9)
998      -x² + 6x -5     -(x - 5)(x - 1)
999    -6x² -19x -10   -(2x + 5)(3x + 2)
1000   -6x² -29x + 5    -(x + 5)(6x - 1)

[1001 rows x 2 columns]